name: azules
display_name: Azules
version: 1.0.0

parent: classic

assets:
  use_parent_assets: false

  css:
    all:
      - id: fonts
        path: assets/css/fonts.css
        priority: 100

      - id: custom-style
        path: assets/css/custom.css
        priority: 200
