services:
  _defaults:
    public: true

  PrestaShop\Module\Psshipping\Domain\Carriers\MbeStandardCarrierConfiguration:
    class: 'PrestaShop\Module\Psshipping\Domain\Carriers\MbeStandardCarrierConfiguration'
    arguments:
      - 'prestashop.core.command_bus'

  PrestaShop\Module\Psshipping\Domain\Carriers\MbePickupCarrierConfiguration:
    class: 'PrestaShop\Module\Psshipping\Domain\Carriers\MbePickupCarrierConfiguration'
    arguments:
      - 'prestashop.core.command_bus'
